-- Agent OS 3.0 additive state. No existing table is dropped or altered.
CREATE TABLE IF NOT EXISTS agent_goals (goal_id UUID PRIMARY KEY, objective TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', autonomous BOOLEAN NOT NULL DEFAULT false, heartbeat_seconds INT NOT NULL DEFAULT 30, session_id UUID, turn_limit INT NOT NULL DEFAULT 100, token_limit INT NOT NULL DEFAULT 100000, time_limit_seconds INT NOT NULL DEFAULT 3600, tool_call_limit INT NOT NULL DEFAULT 500, subagent_limit INT NOT NULL DEFAULT 32, cost_limit_usd NUMERIC(12,6) NOT NULL DEFAULT 10, next_run_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_agent_goals_status ON agent_goals(status);
CREATE TABLE IF NOT EXISTS agent_heartbeats (goal_id UUID PRIMARY KEY REFERENCES agent_goals(goal_id) ON DELETE CASCADE, last_heartbeat TIMESTAMPTZ NOT NULL DEFAULT now(), missed_count INT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS agent_sessions (session_id UUID PRIMARY KEY, parent_session_id UUID REFERENCES agent_sessions(session_id), goal TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'active', backend TEXT NOT NULL DEFAULT 'python', context JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT now(), updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_agent_sessions_parent ON agent_sessions(parent_session_id);
CREATE TABLE IF NOT EXISTS agent_trajectory (event_id UUID PRIMARY KEY, mission_id UUID NOT NULL, task_id UUID, actor TEXT NOT NULL, event_type TEXT NOT NULL, payload JSONB NOT NULL DEFAULT '{}', prev_hash TEXT NOT NULL, event_hash TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_agent_trajectory_mission ON agent_trajectory(mission_id, created_at);
CREATE TABLE IF NOT EXISTS agent_checkpoints (checkpoint_id UUID PRIMARY KEY, mission_id UUID NOT NULL, label TEXT NOT NULL, state JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS harness_items (item_id UUID PRIMARY KEY, kind TEXT NOT NULL, item_key TEXT NOT NULL, value TEXT NOT NULL, version INT NOT NULL DEFAULT 1, enabled BOOLEAN NOT NULL DEFAULT true, updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS harness_refinements (refinement_id UUID PRIMARY KEY, item_id UUID, action TEXT NOT NULL, evidence_ids JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS harness_snapshots (snapshot_id UUID PRIMARY KEY, base_prompt_digest TEXT NOT NULL, state JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS skill_executions (execution_id UUID PRIMARY KEY, skill_id UUID, version INT, status TEXT NOT NULL, input JSONB NOT NULL DEFAULT '{}', output JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS agent_worker_registry (worker_name TEXT PRIMARY KEY, queue_name TEXT NOT NULL, capabilities JSONB NOT NULL DEFAULT '[]', tools JSONB NOT NULL DEFAULT '[]', isolated BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS agent_resource_events (event_id UUID PRIMARY KEY, mission_id UUID, task_id UUID, tokens INT NOT NULL DEFAULT 0, tool_calls INT NOT NULL DEFAULT 0, subagents INT NOT NULL DEFAULT 0, runtime_seconds NUMERIC(12,3) NOT NULL DEFAULT 0, cost_usd NUMERIC(12,6) NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
